apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: hackatoon-rabbitmq
  ports:
    - name: amqp          # Porta para comunica��o AMQP
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management    # Porta para a interface de gerenciamento (HTTP)
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP         # Pode ser NodePort ou LoadBalancer se precisar de acesso externo